 #Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "split45rmk"
product_name = "split45rmk"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "kong"
chip = "nrf52840"

[layout]
rows = 4
cols = 12
layers = 8
keymap = [
    # Layer 0
    [
        ["Esc","Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Backspace"],
        ["Tab","A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Enter"],
        ["LShift","Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Up", "Delete"],
        ["LCtrl", "LGui", "LAlt", "Space","LT(2, Space)", "Left", "Down", "Right", "_", "_", "_", "_"]
    ],
    # Layer 1 (Left half only)
    [
        ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "Equal", "Backspace"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    # Layer 2
       [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    # Layer 3
   [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    # Layer 4 (empty/transparent)
      [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    # Layer 5
      [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    # Layer 6
     [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    # Layer 7
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
]

[rmk]
# Maximum number of combos keyboard can store
combo_max_num = 25
# Maximum number of keys pressed simultaneously in a combo
combo_max_length = 4
# Default debounce time in milliseconds  
debounce_time = 5

[rmk_config]
morse_max_num = 16        # 全局最多支持 16 组独立 TapDance/Morse 按键（按需修改，上限256）
max_patterns_per_key = 10 # 单个 TapDance 按键支持最多 10 连击阶数（单击/双击/三击…）

[behavior.morse] # 摩斯码，通过短按/长按的排列组合，实现不同按键的输出
# default profile for morse, tap dance and tap-hold keys:全局配置
enable_flow_tap = true
prior_idle_time = "120ms"
hold_on_other_press = true
unilateral_false = false
hold_timeout = "250ms"
gap_timeout = "250ms"
patterns = [
    [
"KC_A"
],       # 单击
    [
"KC_B"
],       # 双击
    [
"KC_C"
],       # 三击
    [
"KC_D"
],       # 四击
    # ... 按 morse_max_num 数量继续添加
]


[host]
# Unlock combination: simultaneous press of specified keys
# Format: [[row, col], [row, col], ...]
unlock_keys = [[0, 0], [0, 1]]  # Keys at (row=0,col=0) and (row=0,col=1)

[ble]
enabled = true
battery_adc_pin = "vddh"

[split]
connection = "ble"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]
[split.central.matrix]
matrix_type = "normal"
col_pins = ["P1_15", "P1_13", "P1_11", "P0_10", "P0_09", "P1_04"]
row_pins = ["P1_06", "P0_02", "P0_29", "P0_31"]
# col2row = true

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
[split.peripheral.matrix]
matrix_type = "normal"
col_pins = ["P1_15", "P1_13", "P1_11", "P0_10", "P0_09", "P1_04"]
row_pins = ["P1_06", "P0_02", "P0_29", "P0_31"]
# col2row = true
