[keyboard]
name = "velvet"
product_name = "velvet"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "pkk"
chip = "rp2040"

[keymap]

[keymap.layers.0]
name = "base_layer"
keys = """
Q     W      E      R      T            Y      U      I      O      P
A     S      D      F      G            H      J      K      L      ENTER
Z     X      C      V      B            N      M      COMMA  DOT    SLASH
    LCTL    LALT   LSFT   MO(1)      SPACE   MO(2)   RALT   DEL
"""

[storage]
# clear_storage = true

[split]
connection = "serial"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]

[split.central.matrix]
matrix_type = "normal"
row2col = true
row_pins = ["PIN_2", "PIN_3", "PIN_4", "PIN_5"]
col_pins = ["PIN_9", "PIN_10", "PIN_11", "PIN_12", "PIN_13"]
bootmagic = [0, 0]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]

[split.peripheral.matrix]
matrix_type = "normal"
row2col = true
row_pins = ["PIN_2", "PIN_3", "PIN_4", "PIN_5"]
col_pins = ["PIN_9", "PIN_10", "PIN_11", "PIN_12", "PIN_13"]
bootmagic = [0, 0]

[rmk]
split_peripherals_num = 1
combo_max_num = 25
combo_max_length = 4
debounce_time = 15
morse_max_num = 32
max_patterns_per_key = 4

[host]
insecure = true
