name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv6m-none-eabi

      - name: Install elf2uf2
        run: cargo install elf2uf2-rs

      - name: Build & Generate UF2
        run: cargo build --release --features=rp2040
      
      - name: Output UF2
        run: elf2uf2-rs target/release/*.elf firmware.uf2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            firmware.uf2
            target/release/*.bin
